### ISSUE TITLE
org.eclipse.core.internal.resources.ResourceException after opening external file

### ISSUE THREAD

**Issue by mniewrzal** [pulse00/Composer-Eclipse-Plugin#130]
Just open external file in PHP Editor. Stacktrace:

org.eclipse.core.internal.resources.ResourceException: Resource '/ ' does not exist.
	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:334)
	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:208)
	at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:140)
	at org.eclipse.core.internal.resources.Project.hasNature(Project.java:521)
	at com.dubture.composer.core.build.BuildParticipantFactory.createBuildParticipant(BuildParticipantFactory.java:24)
	at org.eclipse.dltk.internal.core.builder.BuildParticipantManager.createParticipants(BuildParticipantManager.java:202)
	at org.eclipse.dltk.internal.core.builder.BuildParticipantManager.getBuildParticipants(BuildParticipantManager.java:181)
	at org.eclipse.dltk.internal.core.ReconcileBuilder.beginBuild(ReconcileBuilder.java:126)
	at org.eclipse.dltk.internal.core.ReconcileBuilder.run(ReconcileBuilder.java:89)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)

**Comment by zulus** [comment]
Fixed also in other PEX plugins.
