### ISSUE TITLE
Creating new composer project causes CTD on windows 10

### ISSUE THREAD

**Issue by maikgreubel** [pulse00/Composer-Eclipse-Plugin#133]
I want to import an existing composer project fresh cloned from github into eclipse. So I choose "New composer project from existing package" from File menu. Then the IDE becomes unresponsive. I try to change to radio "Create project at existing location" - IDE hangs. After waiting for a while, a crash-to-desktop happens and in .metadata folder a big .log is written. There are many exceptions with same cause:

```
!ENTRY org.eclipse.ui 4 0 2015-11-06 19:15:59.096
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTError: No more handles)
at org.eclipse.swt.SWT.error(SWT.java:4491)
at org.eclipse.swt.SWT.error(SWT.java:4406)
at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
at org.eclipse.jface.window.Window.open(Window.java:803)
at org.eclipse.ui.internal.actions.NewWizardShortcutAction.run(NewWizardShortcutAction.java:136)
at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
Caused by: org.eclipse.swt.SWTError: No more handles
at org.eclipse.swt.SWT.error(SWT.java:4517)
at org.eclipse.swt.SWT.error(SWT.java:4406)
at org.eclipse.swt.SWT.error(SWT.java:4377)
at org.eclipse.swt.graphics.Image.init(Image.java:1987)
at org.eclipse.swt.graphics.Image.init(Image.java:2133)
at org.eclipse.swt.graphics.Image.initNative(Image.java:909)
at org.eclipse.swt.graphics.Image.<init>(Image.java:628)
at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:286)
at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:224)
at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:202)
at com.dubture.composer.ui.wizard.project.template.PackagistItem.createStatsPart(PackagistItem.java:117)
at com.dubture.composer.ui.wizard.project.template.PackagistItem.createContent(PackagistItem.java:93)
at com.dubture.composer.ui.wizard.project.template.PackagistItem.<init>(PackagistItem.java:59)
at com.dubture.composer.ui.wizard.project.template.PackageFilterViewer.doCreateViewerItem(PackageFilterViewer.java:98)
at com.dubture.composer.ui.wizard.project.template.PackageFilterViewer$1.doCreateItem(PackageFilterViewer.java:65)
at org.eclipse.equinox.internal.p2.ui.discovery.util.ControlListViewer.createNewItem(ControlListViewer.java:244)
at org.eclipse.equinox.internal.p2.ui.discovery.util.ControlListViewer.refreshAll(ControlListViewer.java:481)
at org.eclipse.equinox.internal.p2.ui.discovery.util.ControlListViewer.internalRefresh(ControlListViewer.java:365)
at org.eclipse.jface.viewers.StructuredViewer$7.run(StructuredViewer.java:1526)
at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1462)
at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1423)
at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1523)
at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1482)
at com.dubture.composer.ui.wizard.project.template.PackageFilterViewer$3$1.run(PackageFilterViewer.java:137)
at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
... 35 more
```

Creating a blank new composer package is possible without any errors or warnings.

This has happend with version

```
Composer    1.0.2.201510161055  com.dubture.composer.feature.feature.group  https://github.com/pulse00
```

**Comment by zulus** [comment]
Could you tell me which github project you trying to import? I made simple test with FosUserBundle and works perfectly on windows 10.

Also can you put here list of installed features/plugins? Help->About Eclipse->Installation Details->Configuration

**Comment by maikgreubel** [comment]
I tried to import https://github.com/amphp/aerys.git

My configuration is at https://gist.github.com/maikgreubel/b6c225954f35b2352735
