### ISSUE TITLE
Internal error occured during Update

### ISSUE THREAD

**Issue by EuMMCR** [pulse00/Composer-Eclipse-Plugin#138]
Hi,

I just installed the composer plugin via the PDT-Extensions.
Whenever I run an install or update command, an error occurs with the following message:

> An internal error occurred during: "Updating composer dependencies (no-dev)...".
org/eclipse/php/internal/ui/preferences/util/PreferencesSupport

In the Error Log I can see the following Stack Trace:
> java.lang.NoClassDefFoundError: org/eclipse/php/internal/ui/preferences/util/PreferencesSupport
	at org.pdtextensions.core.launch.environment.AbstractEnvironmentFactory.getEnvironment(AbstractEnvironmentFactory.java:16)
	at org.pdtextensions.core.launch.ScriptLauncherManager.getEnvironment(ScriptLauncherManager.java:56)
	at org.pdtextensions.core.launch.ScriptLauncherManager.getLauncher(ScriptLauncherManager.java:64)
	at com.dubture.composer.ui.job.ComposerJob.run(ComposerJob.java:77)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.ClassNotFoundException: org.eclipse.php.internal.ui.preferences.util.PreferencesSupport cannot be found by org.pdtextensions.core_0.22.0.201510021218
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more

Here is my Session data:

> eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

Do I need to install some more dependencies?

Thank you
EuMMCR

**Comment by zulus** [comment]
please run update right now (restart eclipse might be required)

**Comment by EuMMCR** [comment]
Wow, that was very fast...
Thank you very much, it's working perfectly now!
